#ifndef LOGICELEMENTS_GLOBAL_H
#define LOGICELEMENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGICELEMENTS_LIBRARY)
#  define LOGICELEMENTS_EXPORT Q_DECL_EXPORT
#else
#  define LOGICELEMENTS_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGICELEMENTS_GLOBAL_H
